### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Ichigo1174** [codestarterorg/ubuntu-chromebook-installer#13]
Under Usage going from step 5 to step 6 and I am suppose to "Run the script with sudo bash main.sh"
every time I try to access main.sh I get a Permission denied. Anything else gets a "No such file or directory"
![20141231_222433](https://cloud.githubusercontent.com/assets/10361815/5591598/5145a43e-913c-11e4-95c6-e6bde7f51f92.jpg)

**Comment by mojombo** [comment]
There are two separate commands you need to run:

1. `cd /media/removable/Cruzer/ubuntu-chromebook/installer`
2. `sudo bash main.sh`

Give that a try and let me know if it works for you.
