### ISSUE TITLE
Install appears complete but boot stalls on "Booting from Hard Disk"

### ISSUE THREAD

**Issue by kayakr** [codestarterorg/ubuntu-chromebook-installer#14]
Ubuntu install log is at https://gist.github.com/kayakr/a2495201c263749cc1fa

**Comment by mojombo** [comment]
When you restarted after completion, did you remove the USB drive right away? Leaving the USB stick in can cause this.

**Comment by kayakr** [comment]
Yes, that's quite possible. It wasn't clear which reboot required the USB drive to be present and which didn't. Should I restore the system using Chrome recovery media, or is there another way to get things on track?

**Comment by mojombo** [comment]
Yeah, sorry, those instructions need some work. Try just booting with nothing in the USB drive first and see what happens.

**Comment by kayakr** [comment]
I rebooted, and repeated the sudo bash main.sh install. When the machine rebooted I removed the USB drive and Ubuntu has successfully booted, thanks.
