### ISSUE TITLE
After running script, and starting ubuntu I get system running in low graphics mode, then it locks up.

### ISSUE THREAD

**Issue by rkt88edmo** [codestarterorg/ubuntu-chromebook-installer#19]
There is a notification, and then it gives four choices:
Run in low graphics mode for one session
Reconfigure Graphics
Troubleshoot the error
Exit to console login

But I can't seem to change between the choices or accept any of them and finish booting ubuntu.

Version 43.0.2348.81
Platform 6946.55.0
Google_Peppy.4389.89.0

**Comment by mojombo** [comment]
See #18.
