### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by juanpastas** [codestarterorg/ubuntu-chromebook-installer#23]
I tried seeing volume control and indicator does not move.

Any advice?

**Comment by tedmcox** [comment]
I installed and ran pavucontrol:

    $ sudo apt-get install pavucontrol
    $ pavucontrol

Under the Input Devices tab I changed Port to "Microphone (unplugged)".

**Comment by ulisesantana** [comment]
Thanks @tedmcox now it works, but it's very quiet. Anyone also happens the same?
